sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true

git:
  depth: 5

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - echo 'error_reporting = E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - bash <(curl -s https://codecov.io/bash)
