language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

git:
  depth: 5

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
    - bash <(curl -s https://codecov.io/bash)
