sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  include:
    # test against the latest HHVM version by using trusty
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # Use edge image until the next travis CI image update
  allow_failures:
    - php: hhvm

git:
  depth: 5

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - if [[ "$(phpenv version-name)" != "hhvm" ]]; then echo 'error_reporting = E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi

script:
  - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - bash <(curl -s https://codecov.io/bash)
