sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - 7.4snapshot
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

git:
  depth: 5

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - echo 'error_reporting = E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - bash <(curl -s https://codecov.io/bash)
